// Comprehensive dummy data for Travel Planner

export const popularDestinations = [
  {
    id: 1,
    name: "Goa",
    country: "India",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    rating: 4.8,
    reviews: 2345,
    price: 4999,
    tag: "Beaches",
  },
  {
    id: 2,
    name: "Dubai",
    country: "UAE",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    rating: 4.9,
    reviews: 5678,
    price: 25999,
    tag: "Luxury",
  },
  {
    id: 3,
    name: "Manali",
    country: "India",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    rating: 4.7,
    reviews: 1892,
    price: 6999,
    tag: "Mountains",
  },
  {
    id: 4,
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    rating: 4.9,
    reviews: 4521,
    price: 35999,
    tag: "Adventure",
  },
  {
    id: 5,
    name: "Jaipur",
    country: "India",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800",
    rating: 4.6,
    reviews: 3456,
    price: 3999,
    tag: "Heritage",
  },
  {
    id: 6,
    name: "Maldives",
    country: "Maldives",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    rating: 5.0,
    reviews: 2891,
    price: 75999,
    tag: "Honeymoon",
  },
  {
    id: 7,
    name: "Singapore",
    country: "Singapore",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    rating: 4.8,
    reviews: 4123,
    price: 45999,
    tag: "City",
  },
  {
    id: 8,
    name: "Kerala",
    country: "India",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    rating: 4.7,
    reviews: 2567,
    price: 8999,
    tag: "Nature",
  },
];

export const flights = [
  {
    id: "FL001",
    airline: "IndiGo",
    airlineLogo: "https://logos-world.net/wp-content/uploads/2023/01/IndiGo-Logo.png",
    flightNumber: "6E-2341",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    departureTime: "06:00",
    arrivalTime: "08:10",
    duration: "2h 10m",
    stops: 0,
    price: 4599,
    originalPrice: 5999,
    class: "Economy",
    seatsLeft: 5,
    amenities: ["Meal", "WiFi", "Entertainment"],
    baggage: "15kg",
    date: "2024-03-15",
  },
  {
    id: "FL002",
    airline: "Air India",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Air_India_Logo.svg/1200px-Air_India_Logo.svg.png",
    flightNumber: "AI-865",
    from: "Delhi",
    fromCode: "DEL",
    to: "Mumbai",
    toCode: "BOM",
    departureTime: "09:30",
    arrivalTime: "11:45",
    duration: "2h 15m",
    stops: 0,
    price: 5299,
    originalPrice: 6499,
    class: "Economy",
    seatsLeft: 12,
    amenities: ["Meal", "WiFi", "Entertainment", "Priority Boarding"],
    baggage: "25kg",
    date: "2024-03-15",
  },
  {
    id: "FL003",
    airline: "Vistara",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png",
    flightNumber: "UK-945",
    from: "Delhi",
    fromCode: "DEL",
    to: "Goa",
    toCode: "GOI",
    departureTime: "14:20",
    arrivalTime: "16:45",
    duration: "2h 25m",
    stops: 0,
    price: 6899,
    originalPrice: 8999,
    class: "Economy",
    seatsLeft: 8,
    amenities: ["Meal", "WiFi", "Entertainment", "Lounge Access"],
    baggage: "20kg",
    date: "2024-03-15",
  },
  {
    id: "FL004",
    airline: "SpiceJet",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/SpiceJet_logo.svg/1200px-SpiceJet_logo.svg.png",
    flightNumber: "SG-8127",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Dubai",
    toCode: "DXB",
    departureTime: "23:55",
    arrivalTime: "02:10",
    duration: "3h 15m",
    stops: 0,
    price: 12999,
    originalPrice: 15999,
    class: "Economy",
    seatsLeft: 15,
    amenities: ["Meal", "Entertainment"],
    baggage: "20kg",
    date: "2024-03-16",
  },
  {
    id: "FL005",
    airline: "Emirates",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Emirates_logo.svg/1200px-Emirates_logo.svg.png",
    flightNumber: "EK-505",
    from: "Delhi",
    fromCode: "DEL",
    to: "Dubai",
    toCode: "DXB",
    departureTime: "03:45",
    arrivalTime: "05:55",
    duration: "3h 40m",
    stops: 0,
    price: 18999,
    originalPrice: 24999,
    class: "Business",
    seatsLeft: 4,
    amenities: ["Premium Meal", "WiFi", "Entertainment", "Lounge Access", "Priority Boarding", "Flat Bed"],
    baggage: "35kg",
    date: "2024-03-16",
  },
  {
    id: "FL006",
    airline: "IndiGo",
    airlineLogo: "https://logos-world.net/wp-content/uploads/2023/01/IndiGo-Logo.png",
    flightNumber: "6E-5532",
    from: "Bangalore",
    fromCode: "BLR",
    to: "Delhi",
    toCode: "DEL",
    departureTime: "07:15",
    arrivalTime: "09:55",
    duration: "2h 40m",
    stops: 0,
    price: 4299,
    originalPrice: 5499,
    class: "Economy",
    seatsLeft: 22,
    amenities: ["Meal"],
    baggage: "15kg",
    date: "2024-03-15",
  },
  {
    id: "FL007",
    airline: "Air India",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Air_India_Logo.svg/1200px-Air_India_Logo.svg.png",
    flightNumber: "AI-143",
    from: "Delhi",
    fromCode: "DEL",
    to: "Singapore",
    toCode: "SIN",
    departureTime: "11:30",
    arrivalTime: "19:45",
    duration: "5h 45m",
    stops: 0,
    price: 22999,
    originalPrice: 28999,
    class: "Economy",
    seatsLeft: 9,
    amenities: ["Meal", "WiFi", "Entertainment", "Priority Boarding"],
    baggage: "30kg",
    date: "2024-03-17",
  },
  {
    id: "FL008",
    airline: "Vistara",
    airlineLogo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Vistara_Logo.svg/1200px-Vistara_Logo.svg.png",
    flightNumber: "UK-821",
    from: "Mumbai",
    fromCode: "BOM",
    to: "Goa",
    toCode: "GOI",
    departureTime: "16:00",
    arrivalTime: "17:15",
    duration: "1h 15m",
    stops: 0,
    price: 3999,
    originalPrice: 4999,
    class: "Economy",
    seatsLeft: 18,
    amenities: ["Meal", "Entertainment"],
    baggage: "15kg",
    date: "2024-03-15",
  },
];

// NEW: Trains data
export const trains = [
  {
    id: "TR001",
    name: "Rajdhani Express",
    trainNumber: "12952",
    from: "Delhi",
    fromStation: "New Delhi Railway Station",
    fromCode: "NDLS",
    to: "Mumbai",
    toStation: "Mumbai Central",
    toCode: "MMCT",
    departureTime: "16:55",
    arrivalTime: "08:35",
    duration: "15h 40m",
    daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    classes: [
      { type: "1A", name: "First AC", price: 4745, available: 12 },
      { type: "2A", name: "Second AC", price: 2770, available: 45 },
      { type: "3A", name: "Third AC", price: 1925, available: 120 },
    ],
    amenities: ["Pantry", "Bedding", "Charging Points"],
    rating: 4.5,
    reviews: 2456,
  },
  {
    id: "TR002",
    name: "Shatabdi Express",
    trainNumber: "12002",
    from: "Delhi",
    fromStation: "New Delhi Railway Station",
    fromCode: "NDLS",
    to: "Bhopal",
    toStation: "Bhopal Junction",
    toCode: "BPL",
    departureTime: "06:00",
    arrivalTime: "13:50",
    duration: "7h 50m",
    daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    classes: [
      { type: "EC", name: "Executive Chair", price: 2130, available: 24 },
      { type: "CC", name: "AC Chair Car", price: 1090, available: 180 },
    ],
    amenities: ["Meals Included", "Charging Points", "Newspapers"],
    rating: 4.3,
    reviews: 1892,
  },
  {
    id: "TR003",
    name: "Duronto Express",
    trainNumber: "12213",
    from: "Mumbai",
    fromStation: "Mumbai Central",
    fromCode: "MMCT",
    to: "Delhi",
    toStation: "Hazrat Nizamuddin",
    toCode: "NZM",
    departureTime: "23:15",
    arrivalTime: "16:15",
    duration: "17h 00m",
    daysOfWeek: ["Mon", "Wed", "Fri", "Sun"],
    classes: [
      { type: "1A", name: "First AC", price: 5245, available: 8 },
      { type: "2A", name: "Second AC", price: 3070, available: 32 },
      { type: "3A", name: "Third AC", price: 2125, available: 96 },
      { type: "SL", name: "Sleeper", price: 755, available: 200 },
    ],
    amenities: ["Pantry", "Bedding", "No Stops"],
    rating: 4.4,
    reviews: 1567,
  },
  {
    id: "TR004",
    name: "Gatimaan Express",
    trainNumber: "12050",
    from: "Delhi",
    fromStation: "Hazrat Nizamuddin",
    fromCode: "NZM",
    to: "Agra",
    toStation: "Agra Cantt",
    toCode: "AGC",
    departureTime: "08:10",
    arrivalTime: "09:50",
    duration: "1h 40m",
    daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    classes: [
      { type: "EC", name: "Executive Chair", price: 1500, available: 32 },
      { type: "CC", name: "AC Chair Car", price: 755, available: 250 },
    ],
    amenities: ["WiFi", "Meals Included", "LCD Screens", "180 km/h Speed"],
    rating: 4.7,
    reviews: 3421,
  },
  {
    id: "TR005",
    name: "Vande Bharat Express",
    trainNumber: "22436",
    from: "Delhi",
    fromStation: "New Delhi Railway Station",
    fromCode: "NDLS",
    to: "Varanasi",
    toStation: "Varanasi Junction",
    toCode: "BSB",
    departureTime: "06:00",
    arrivalTime: "14:00",
    duration: "8h 00m",
    daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    classes: [
      { type: "EC", name: "Executive Chair", price: 2445, available: 42 },
      { type: "CC", name: "AC Chair Car", price: 1285, available: 320 },
    ],
    amenities: ["WiFi", "Bio-Vacuum Toilets", "GPS Info", "Meals Included", "160 km/h Speed"],
    rating: 4.8,
    reviews: 4567,
  },
  {
    id: "TR006",
    name: "Howrah Rajdhani",
    trainNumber: "12302",
    from: "Delhi",
    fromStation: "New Delhi Railway Station",
    fromCode: "NDLS",
    to: "Kolkata",
    toStation: "Howrah Junction",
    toCode: "HWH",
    departureTime: "16:55",
    arrivalTime: "09:55",
    duration: "17h 00m",
    daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    classes: [
      { type: "1A", name: "First AC", price: 5150, available: 16 },
      { type: "2A", name: "Second AC", price: 3015, available: 52 },
      { type: "3A", name: "Third AC", price: 2085, available: 140 },
    ],
    amenities: ["Pantry", "Bedding", "Charging Points"],
    rating: 4.5,
    reviews: 2890,
  },
];

// NEW: Cabs data
export const cabs = [
  {
    id: "CB001",
    type: "Sedan",
    name: "Swift Dzire",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
    capacity: 4,
    luggage: 2,
    ac: true,
    fuelType: "Petrol/CNG",
    pricePerKm: 12,
    baseFare: 299,
    perKmRate: 12,
    driverAllowance: 300,
    nightCharges: 250,
    features: ["AC", "4 Seater", "2 Bags", "Music System"],
    rating: 4.3,
    reviews: 5678,
  },
  {
    id: "CB002",
    type: "Sedan",
    name: "Honda Amaze",
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
    capacity: 4,
    luggage: 2,
    ac: true,
    fuelType: "Petrol",
    pricePerKm: 14,
    baseFare: 349,
    perKmRate: 14,
    driverAllowance: 300,
    nightCharges: 250,
    features: ["AC", "4 Seater", "2 Bags", "Music System", "USB Charging"],
    rating: 4.4,
    reviews: 4321,
  },
  {
    id: "CB003",
    type: "SUV",
    name: "Toyota Innova",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400",
    capacity: 6,
    luggage: 4,
    ac: true,
    fuelType: "Diesel",
    pricePerKm: 18,
    baseFare: 499,
    perKmRate: 18,
    driverAllowance: 400,
    nightCharges: 300,
    features: ["AC", "6 Seater", "4 Bags", "Music System", "USB Charging", "Extra Legroom"],
    rating: 4.6,
    reviews: 8912,
  },
  {
    id: "CB004",
    type: "SUV",
    name: "Innova Crysta",
    image: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400",
    capacity: 7,
    luggage: 4,
    ac: true,
    fuelType: "Diesel",
    pricePerKm: 22,
    baseFare: 599,
    perKmRate: 22,
    driverAllowance: 400,
    nightCharges: 350,
    features: ["AC", "7 Seater", "4 Bags", "Captain Seats", "USB Charging", "Premium Interior"],
    rating: 4.7,
    reviews: 6543,
  },
  {
    id: "CB005",
    type: "Luxury",
    name: "Mercedes E-Class",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=400",
    capacity: 4,
    luggage: 2,
    ac: true,
    fuelType: "Petrol",
    pricePerKm: 45,
    baseFare: 1999,
    perKmRate: 45,
    driverAllowance: 600,
    nightCharges: 500,
    features: ["Premium AC", "4 Seater", "Leather Seats", "WiFi", "Water Bottles", "Professional Chauffeur"],
    rating: 4.9,
    reviews: 2345,
  },
  {
    id: "CB006",
    type: "Tempo Traveller",
    name: "Force Traveller",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400",
    capacity: 12,
    luggage: 8,
    ac: true,
    fuelType: "Diesel",
    pricePerKm: 25,
    baseFare: 1499,
    perKmRate: 25,
    driverAllowance: 500,
    nightCharges: 400,
    features: ["AC", "12 Seater", "Push Back Seats", "Music System", "Ample Luggage Space"],
    rating: 4.4,
    reviews: 3456,
  },
];

// Popular cab routes with estimated prices
export const popularCabRoutes = [
  { from: "Delhi", to: "Agra", distance: 233, duration: "3h 30m" },
  { from: "Delhi", to: "Jaipur", distance: 281, duration: "4h 30m" },
  { from: "Mumbai", to: "Pune", distance: 148, duration: "2h 30m" },
  { from: "Mumbai", to: "Lonavala", distance: 83, duration: "1h 45m" },
  { from: "Bangalore", to: "Mysore", distance: 150, duration: "3h 00m" },
  { from: "Chennai", to: "Pondicherry", distance: 170, duration: "3h 15m" },
  { from: "Delhi", to: "Manali", distance: 540, duration: "12h 00m" },
  { from: "Delhi", to: "Shimla", distance: 350, duration: "7h 00m" },
];

export const hotels = [
  {
    id: "HT001",
    name: "The Taj Mahal Palace",
    location: "Mumbai, Maharashtra",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    ],
    rating: 4.9,
    reviews: 4521,
    price: 15999,
    originalPrice: 22999,
    perNight: true,
    stars: 5,
    amenities: ["Pool", "Spa", "WiFi", "Restaurant", "Gym", "Bar", "Room Service", "Parking"],
    roomTypes: [
      { type: "Deluxe Room", price: 15999, capacity: 2 },
      { type: "Premium Suite", price: 28999, capacity: 3 },
      { type: "Presidential Suite", price: 85999, capacity: 4 },
    ],
    description: "An iconic luxury hotel overlooking the Gateway of India and the Arabian Sea.",
    coordinates: { lat: 18.9217, lng: 72.8332 },
  },
  {
    id: "HT002",
    name: "Alila Fort Bishangarh",
    location: "Jaipur, Rajasthan",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800",
    ],
    rating: 4.8,
    reviews: 1892,
    price: 18999,
    originalPrice: 25999,
    perNight: true,
    stars: 5,
    amenities: ["Pool", "Spa", "WiFi", "Restaurant", "Heritage Tours", "Yoga"],
    roomTypes: [
      { type: "Grand Suite", price: 18999, capacity: 2 },
      { type: "Royal Suite", price: 35999, capacity: 2 },
    ],
    description: "A stunning heritage fort hotel with panoramic views of the Aravalli Hills.",
    coordinates: { lat: 27.6017, lng: 75.8155 },
  },
  {
    id: "HT003",
    name: "W Goa",
    location: "North Goa, India",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
    images: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800",
    ],
    rating: 4.7,
    reviews: 2156,
    price: 12999,
    originalPrice: 18999,
    perNight: true,
    stars: 5,
    amenities: ["Beach Access", "Pool", "Spa", "WiFi", "Restaurant", "Bar", "Nightclub"],
    roomTypes: [
      { type: "Wonderful Room", price: 12999, capacity: 2 },
      { type: "Spectacular Room", price: 18999, capacity: 2 },
      { type: "WOW Suite", price: 45999, capacity: 4 },
    ],
    description: "A vibrant beachside retreat perfect for fun-seekers.",
    coordinates: { lat: 15.5524, lng: 73.7614 },
  },
  {
    id: "HT004",
    name: "Burj Al Arab Jumeirah",
    location: "Dubai, UAE",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
    ],
    rating: 5.0,
    reviews: 6789,
    price: 125999,
    originalPrice: 175999,
    perNight: true,
    stars: 7,
    amenities: ["Private Beach", "Pool", "Helipad", "Spa", "Butler Service", "Restaurants", "Chauffeur"],
    roomTypes: [
      { type: "Deluxe Suite", price: 125999, capacity: 2 },
      { type: "Panoramic Suite", price: 225999, capacity: 4 },
      { type: "Royal Suite", price: 899999, capacity: 6 },
    ],
    description: "The world's most luxurious hotel, shaped like a sail.",
    coordinates: { lat: 25.1412, lng: 55.1854 },
  },
  {
    id: "HT005",
    name: "Treebo Trend Urban Oasis",
    location: "Delhi, India",
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    images: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800",
    ],
    rating: 4.2,
    reviews: 892,
    price: 2499,
    originalPrice: 3999,
    perNight: true,
    stars: 3,
    amenities: ["WiFi", "AC", "TV", "Room Service"],
    roomTypes: [
      { type: "Standard Room", price: 2499, capacity: 2 },
      { type: "Deluxe Room", price: 3499, capacity: 2 },
    ],
    description: "A budget-friendly hotel in the heart of Delhi.",
    coordinates: { lat: 28.6139, lng: 77.209 },
  },
  {
    id: "HT006",
    name: "The Leela Palace",
    location: "Bangalore, Karnataka",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
    ],
    rating: 4.8,
    reviews: 3456,
    price: 14999,
    originalPrice: 19999,
    perNight: true,
    stars: 5,
    amenities: ["Pool", "Spa", "WiFi", "Multiple Restaurants", "Gym", "Business Center"],
    roomTypes: [
      { type: "Premiere Room", price: 14999, capacity: 2 },
      { type: "Royal Club Room", price: 22999, capacity: 2 },
    ],
    description: "Opulent luxury in the Garden City.",
    coordinates: { lat: 12.9619, lng: 77.6495 },
  },
  {
    id: "HT007",
    name: "Kumarakom Lake Resort",
    location: "Kerala, India",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    images: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    ],
    rating: 4.9,
    reviews: 2134,
    price: 22999,
    originalPrice: 29999,
    perNight: true,
    stars: 5,
    amenities: ["Lake View", "Pool", "Spa", "Ayurveda", "Houseboat", "Restaurant"],
    roomTypes: [
      { type: "Heritage Pool Villa", price: 22999, capacity: 2 },
      { type: "Luxury Pavilion", price: 32999, capacity: 2 },
    ],
    description: "A serene backwater resort with traditional Kerala architecture.",
    coordinates: { lat: 9.6175, lng: 76.4301 },
  },
  {
    id: "HT008",
    name: "OYO Townhouse",
    location: "Goa, India",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    images: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
    ],
    rating: 4.0,
    reviews: 567,
    price: 1999,
    originalPrice: 2999,
    perNight: true,
    stars: 2,
    amenities: ["WiFi", "AC", "TV", "Breakfast"],
    roomTypes: [
      { type: "Standard Room", price: 1999, capacity: 2 },
    ],
    description: "Affordable stays near the beach.",
    coordinates: { lat: 15.2993, lng: 74.124 },
  },
];

export const activities = [
  {
    id: "AC001",
    name: "Scuba Diving Adventure",
    location: "Goa, India",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800",
    rating: 4.8,
    reviews: 1245,
    price: 3999,
    originalPrice: 5999,
    duration: "3 hours",
    category: "Adventure",
    includes: ["Equipment", "Instructor", "Photos", "Refreshments"],
    description: "Explore the underwater world with certified instructors.",
  },
  {
    id: "AC002",
    name: "Desert Safari with BBQ",
    location: "Dubai, UAE",
    image: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800",
    rating: 4.9,
    reviews: 3456,
    price: 4999,
    originalPrice: 6999,
    duration: "6 hours",
    category: "Adventure",
    includes: ["Dune Bashing", "Camel Ride", "BBQ Dinner", "Entertainment", "Hotel Pickup"],
    description: "Experience the thrill of dune bashing followed by a traditional BBQ.",
  },
  {
    id: "AC003",
    name: "Taj Mahal Sunrise Tour",
    location: "Agra, India",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800",
    rating: 4.9,
    reviews: 5678,
    price: 2499,
    originalPrice: 3499,
    duration: "4 hours",
    category: "Cultural",
    includes: ["Guide", "Entry Tickets", "Breakfast", "Transport"],
    description: "Witness the iconic Taj Mahal at sunrise in all its glory.",
  },
  {
    id: "AC004",
    name: "Bali Swing & Rice Terrace",
    location: "Bali, Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    rating: 4.7,
    reviews: 2345,
    price: 1999,
    originalPrice: 2999,
    duration: "5 hours",
    category: "Nature",
    includes: ["Swing Access", "Lunch", "Rice Terrace Visit", "Transport"],
    description: "Swing over the jungle and explore stunning rice terraces.",
  },
  {
    id: "AC005",
    name: "Kerala Backwater Cruise",
    location: "Kerala, India",
    image: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=800",
    rating: 4.8,
    reviews: 1892,
    price: 5999,
    originalPrice: 7999,
    duration: "8 hours",
    category: "Nature",
    includes: ["Houseboat", "All Meals", "Guide", "Village Visit"],
    description: "Cruise through the serene backwaters on a traditional houseboat.",
  },
  {
    id: "AC006",
    name: "Paragliding in Manali",
    location: "Manali, India",
    image: "https://images.unsplash.com/photo-1503507604906-a4c79fe9cb93?w=800",
    rating: 4.6,
    reviews: 1567,
    price: 2999,
    originalPrice: 4499,
    duration: "30 mins",
    category: "Adventure",
    includes: ["Equipment", "Pilot", "Photos", "Certificate"],
    description: "Soar over the beautiful Himalayan valleys.",
  },
  {
    id: "AC007",
    name: "Singapore Night Safari",
    location: "Singapore",
    image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800",
    rating: 4.7,
    reviews: 4123,
    price: 3499,
    originalPrice: 4499,
    duration: "4 hours",
    category: "Wildlife",
    includes: ["Entry Ticket", "Tram Ride", "Shows"],
    description: "Experience the world's first nocturnal wildlife park.",
  },
  {
    id: "AC008",
    name: "Jaipur Food Walk",
    location: "Jaipur, India",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    rating: 4.8,
    reviews: 987,
    price: 999,
    originalPrice: 1499,
    duration: "3 hours",
    category: "Food",
    includes: ["Guide", "Food Tastings", "Drinks"],
    description: "Explore the vibrant street food scene of Pink City.",
  },
];

export const deals = [
  {
    id: 1,
    title: "Goa Beach Escape",
    subtitle: "Flight + Hotel + Activities",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    price: 14999,
    originalPrice: 24999,
    discount: 40,
    duration: "3N/4D",
    validTill: "2024-03-31",
  },
  {
    id: 2,
    title: "Dubai Luxury Package",
    subtitle: "Flight + 5-Star Hotel + Desert Safari",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    price: 45999,
    originalPrice: 75999,
    discount: 39,
    duration: "4N/5D",
    validTill: "2024-04-15",
  },
  {
    id: 3,
    title: "Kerala Backwaters",
    subtitle: "Houseboat + Resort Stay",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    price: 18999,
    originalPrice: 29999,
    discount: 37,
    duration: "4N/5D",
    validTill: "2024-03-25",
  },
  {
    id: 4,
    title: "Manali Adventure",
    subtitle: "Hotel + Paragliding + Rafting",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800",
    price: 12999,
    originalPrice: 19999,
    discount: 35,
    duration: "3N/4D",
    validTill: "2024-04-30",
  },
];

export const userTrips = [
  {
    id: "TR001",
    name: "Italy Summer Adventure",
    coverImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800",
    startDate: "2026-06-15",
    endDate: "2026-06-22",
    destinations: ["Rome", "Florence", "Venice"],
    destination: "Italy",
    status: "planning",
    budget: {
      total: 200000,
      spent: 85000,
      planned: 120000,
      currency: "INR",
      categories: {
        flights: 45000,
        hotels: 25000,
        activities: 10000,
        food: 5000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
      { id: 2, name: "Jane Smith", email: "jane@email.com", avatar: "https://i.pravatar.cc/150?img=2", role: "editor" },
      { id: 3, name: "Mike Johnson", email: "mike@email.com", avatar: "https://i.pravatar.cc/150?img=3", role: "planner" },
      { id: 4, name: "Sarah Wilson", email: "sarah@email.com", avatar: "https://i.pravatar.cc/150?img=4", role: "viewer" },
    ],
    itinerary: [
      {
        day: 1,
        date: "2026-06-15",
        items: [
          { id: 1, type: "flight", title: "Delhi to Rome", time: "06:00", endTime: "14:30", location: "Fiumicino Airport", description: "Emirates EK-505 via Dubai", cost: 45000, status: "confirmed" },
          { id: 2, type: "hotel", title: "Check-in Hotel Artemide", time: "16:00", location: "Via Nazionale, Rome", description: "Deluxe Room with Breakfast", cost: 8500, status: "confirmed" },
          { id: 3, type: "activity", title: "Colosseum Evening Walk", time: "18:30", location: "Colosseum", description: "Guided exterior tour", cost: 2000, status: "pending" },
        ],
      },
      {
        day: 2,
        date: "2026-06-16",
        items: [
          { id: 4, type: "activity", title: "Vatican Museums Tour", time: "09:00", endTime: "14:00", location: "Vatican City", description: "Skip-the-line guided tour", cost: 4500, status: "confirmed" },
          { id: 5, type: "food", title: "Lunch at Pizzarium", time: "14:30", location: "Via della Meloria", description: "Famous Roman pizza", cost: 800, status: "pending" },
          { id: 6, type: "activity", title: "Trevi Fountain & Spanish Steps", time: "17:00", location: "Centro Storico", description: "Evening walk and gelato", cost: 500, status: "pending" },
        ],
      },
      {
        day: 3,
        date: "2026-06-17",
        items: [
          { id: 7, type: "transport", title: "Train to Florence", time: "09:00", endTime: "10:30", location: "Roma Termini → Firenze SMN", description: "Frecciarossa High-Speed", cost: 3500, status: "confirmed" },
          { id: 8, type: "hotel", title: "Check-in Hotel Brunelleschi", time: "12:00", location: "Piazza Santa Elisabetta", description: "Classic Room", cost: 9000, status: "confirmed" },
          { id: 9, type: "activity", title: "Uffizi Gallery", time: "15:00", endTime: "18:00", location: "Piazzale degli Uffizi", description: "Renaissance masterpieces", cost: 2500, status: "pending" },
        ],
      },
    ],
    expenses: [
      { id: 1, category: "flights", description: "Delhi to Rome - Emirates", amount: 45000, date: "2026-03-01" },
      { id: 2, category: "hotels", description: "Hotel Artemide Rome - 2 nights", amount: 17000, date: "2026-03-15" },
      { id: 3, category: "hotels", description: "Hotel Brunelleschi Florence", amount: 9000, date: "2026-03-15" },
      { id: 4, category: "activities", description: "Vatican Tour Booking", amount: 4500, date: "2026-04-01" },
    ],
    tags: ["europe", "culture", "summer"],
  },
  {
    id: "TR002",
    name: "Bali Beach Retreat",
    coverImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    startDate: "2026-02-10",
    endDate: "2026-02-17",
    destinations: ["Bali", "Ubud", "Seminyak"],
    destination: "Indonesia",
    status: "upcoming",
    budget: {
      total: 150000,
      spent: 95000,
      planned: 130000,
      currency: "INR",
      categories: {
        flights: 55000,
        hotels: 30000,
        activities: 8000,
        food: 2000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
      { id: 2, name: "Jane Smith", email: "jane@email.com", avatar: "https://i.pravatar.cc/150?img=2", role: "editor" },
    ],
    itinerary: [
      {
        day: 1,
        date: "2026-02-10",
        items: [
          { id: 1, type: "flight", title: "Delhi to Bali", time: "02:00", endTime: "13:30", location: "Ngurah Rai Airport", description: "Singapore Airlines via Singapore", cost: 55000, status: "confirmed" },
          { id: 2, type: "hotel", title: "Check-in COMO Uma Ubud", time: "15:00", location: "Ubud", description: "Terrace Suite with pool view", cost: 15000, status: "confirmed" },
          { id: 3, type: "activity", title: "Sunset at Tegallalang Rice Terraces", time: "17:00", location: "Tegallalang", description: "Iconic Bali rice terraces", cost: 500, status: "pending" },
        ],
      },
      {
        day: 2,
        date: "2026-02-11",
        items: [
          { id: 4, type: "activity", title: "Morning Yoga & Spa", time: "07:00", endTime: "10:00", location: "COMO Shambhala Estate", description: "Wellness retreat session", cost: 3000, status: "confirmed" },
          { id: 5, type: "activity", title: "Ubud Monkey Forest", time: "14:00", location: "Sacred Monkey Forest", description: "Nature walk with macaques", cost: 400, status: "pending" },
          { id: 6, type: "food", title: "Dinner at Locavore", time: "19:00", location: "Jl. Dewisita", description: "Fine dining farm-to-table", cost: 2500, status: "confirmed" },
        ],
      },
    ],
    expenses: [
      { id: 1, category: "flights", description: "Delhi to Bali - Singapore Airlines", amount: 55000, date: "2026-01-05" },
      { id: 2, category: "hotels", description: "COMO Uma Ubud - 4 nights", amount: 30000, date: "2026-01-10" },
      { id: 3, category: "activities", description: "Spa Package", amount: 8000, date: "2026-01-15" },
    ],
    tags: ["beach", "wellness", "honeymoon"],
  },
  {
    id: "TR003",
    name: "Tokyo Conference 2026",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    startDate: "2026-03-15",
    endDate: "2026-03-20",
    destinations: ["Tokyo"],
    destination: "Japan",
    status: "upcoming",
    budget: {
      total: 180000,
      spent: 120000,
      planned: 165000,
      currency: "INR",
      categories: {
        flights: 65000,
        hotels: 45000,
        activities: 8000,
        food: 2000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
    ],
    itinerary: [
      {
        day: 1,
        date: "2026-03-15",
        items: [
          { id: 1, type: "flight", title: "Delhi to Tokyo", time: "23:55", endTime: "12:30", location: "Narita Airport", description: "ANA Direct Flight", cost: 65000, status: "confirmed" },
          { id: 2, type: "hotel", title: "Check-in Park Hyatt Tokyo", time: "15:00", location: "Shinjuku", description: "Park King Room - Lost in Translation hotel!", cost: 22500, status: "confirmed" },
        ],
      },
      {
        day: 2,
        date: "2026-03-16",
        items: [
          { id: 3, type: "activity", title: "Tech Conference Day 1", time: "09:00", endTime: "18:00", location: "Tokyo Big Sight", description: "AI & Future Tech Summit", cost: 0, status: "confirmed" },
          { id: 4, type: "food", title: "Team Dinner at Sukiyabashi Jiro", time: "20:00", location: "Ginza", description: "Michelin 3-star sushi", cost: 8000, status: "confirmed" },
        ],
      },
      {
        day: 3,
        date: "2026-03-17",
        items: [
          { id: 5, type: "activity", title: "Tech Conference Day 2", time: "09:00", endTime: "17:00", location: "Tokyo Big Sight", description: "Networking & Workshops", cost: 0, status: "confirmed" },
          { id: 6, type: "activity", title: "Shibuya Night Exploration", time: "19:00", location: "Shibuya", description: "Crossing, Hachiko & nightlife", cost: 2000, status: "pending" },
        ],
      },
    ],
    expenses: [
      { id: 1, category: "flights", description: "Delhi to Tokyo - ANA", amount: 65000, date: "2026-02-01" },
      { id: 2, category: "hotels", description: "Park Hyatt Tokyo - 5 nights", amount: 45000, date: "2026-02-10" },
      { id: 3, category: "activities", description: "Conference Registration", amount: 8000, date: "2026-02-15" },
    ],
    tags: ["business", "conference", "solo"],
  },
  {
    id: "TR004",
    name: "Goa Beach Vacation",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    startDate: "2026-04-20",
    endDate: "2026-04-24",
    destinations: ["Goa"],
    destination: "India",
    status: "ongoing",
    budget: {
      total: 50000,
      spent: 35000,
      planned: 48000,
      currency: "INR",
      categories: {
        flights: 12000,
        hotels: 15000,
        activities: 5000,
        food: 3000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
      { id: 2, name: "Jane Smith", email: "jane@email.com", avatar: "https://i.pravatar.cc/150?img=2", role: "editor" },
    ],
    itinerary: [
      {
        day: 1,
        date: "2026-04-20",
        items: [
          { id: 1, type: "flight", title: "Delhi to Goa", time: "06:00", location: "Dabolim Airport", description: "IndiGo 6E-2341", cost: 6000, status: "confirmed" },
          { id: 2, type: "hotel", title: "Check-in W Goa", time: "14:00", location: "Vagator", description: "Wonderful Room", cost: 12999, status: "confirmed" },
          { id: 3, type: "activity", title: "Beach Sunset", time: "17:00", location: "Calangute Beach", description: "Evening relaxation", cost: 0, status: "confirmed" },
        ],
      },
      {
        day: 2,
        date: "2026-04-21",
        items: [
          { id: 4, type: "activity", title: "Scuba Diving", time: "09:00", location: "Grande Island", description: "PADI certified dive", cost: 3999, status: "confirmed" },
          { id: 5, type: "food", title: "Lunch at Fisherman's Wharf", time: "13:00", location: "Cavelossim", description: "Seafood feast", cost: 1500, status: "confirmed" },
          { id: 6, type: "activity", title: "Casino Night", time: "20:00", location: "Deltin Royale", description: "Gaming & entertainment", cost: 2000, status: "pending" },
        ],
      },
    ],
    expenses: [
      { id: 1, category: "flights", description: "Delhi to Goa - IndiGo", amount: 6000, date: "2026-03-01" },
      { id: 2, category: "flights", description: "Goa to Delhi - Vistara", amount: 6000, date: "2026-03-01" },
      { id: 3, category: "hotels", description: "W Goa - 4 nights", amount: 15000, date: "2026-03-05" },
      { id: 4, category: "activities", description: "Scuba Diving", amount: 3999, date: "2026-03-05" },
    ],
    tags: ["beach", "adventure", "friends"],
  },
  {
    id: "TR005",
    name: "Kerala Honeymoon",
    coverImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    startDate: "2025-12-10",
    endDate: "2025-12-17",
    destinations: ["Kochi", "Munnar", "Alleppey"],
    destination: "India",
    status: "completed",
    budget: {
      total: 80000,
      spent: 72000,
      planned: 72000,
      currency: "INR",
      categories: {
        flights: 18000,
        hotels: 35000,
        activities: 12000,
        food: 7000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
      { id: 3, name: "Sarah Doe", email: "sarah@email.com", avatar: "https://i.pravatar.cc/150?img=3", role: "editor" },
    ],
    itinerary: [],
    expenses: [],
    tags: ["honeymoon", "nature", "romantic"],
  },
  {
    id: "TR006",
    name: "Rajasthan Heritage Tour",
    coverImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800",
    startDate: "2026-01-01",
    endDate: "2026-01-05",
    destinations: ["Jaipur", "Udaipur", "Jodhpur"],
    destination: "India",
    status: "completed",
    budget: {
      total: 60000,
      spent: 55000,
      planned: 55000,
      currency: "INR",
      categories: {
        flights: 10000,
        hotels: 25000,
        activities: 12000,
        food: 8000,
        transport: 0,
        other: 0,
      },
    },
    collaborators: [
      { id: 1, name: "John Doe", email: "john@email.com", avatar: "https://i.pravatar.cc/150?img=1", role: "owner" },
      { id: 4, name: "Mike Wilson", email: "mike@email.com", avatar: "https://i.pravatar.cc/150?img=4", role: "viewer" },
      { id: 5, name: "Emily Brown", email: "emily@email.com", avatar: "https://i.pravatar.cc/150?img=5", role: "editor" },
    ],
    itinerary: [],
    expenses: [],
    tags: ["heritage", "culture", "photography"],
  },
];

export const recommendations = [
  {
    id: 1,
    title: "Best Time to Visit Goa",
    type: "tip",
    category: "Popular",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    content: "November to February offers perfect weather with temperatures between 20-32°C.",
  },
  {
    id: 2,
    title: "Dubai Visa Requirements",
    type: "visa",
    category: "Info",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    content: "Indians can get visa on arrival for 14 days. Apply online for longer stays.",
  },
  {
    id: 3,
    title: "Budget-Friendly Bali",
    type: "budget",
    category: "Budget",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    content: "Stay in Ubud for cheaper accommodations. Average daily budget: ₹3000-4000.",
  },
  {
    id: 4,
    title: "Luxury Maldives Resorts",
    type: "luxury",
    category: "Luxury",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800",
    content: "Book overwater villas 3-4 months in advance for best rates.",
  },
  {
    id: 5,
    title: "Singapore Currency Tips",
    type: "currency",
    category: "Info",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800",
    content: "1 SGD ≈ ₹62. Use Wise or forex cards for best exchange rates.",
  },
  {
    id: 6,
    title: "Safety in Thailand",
    type: "safety",
    category: "Popular",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800",
    content: "Generally safe for tourists. Be cautious of scams near tourist attractions.",
  },
];

export const notifications = [
  {
    id: 1,
    type: "flight",
    title: "Flight Price Drop Alert",
    message: "Delhi to Goa flights dropped by ₹2,000",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "weather",
    title: "Weather Update",
    message: "Heavy rain expected in Mumbai tomorrow",
    time: "5 hours ago",
    read: false,
  },
  {
    id: 3,
    type: "budget",
    title: "Budget Alert",
    message: "You've spent 70% of your Goa trip budget",
    time: "1 day ago",
    read: true,
  },
  {
    id: 4,
    type: "group",
    title: "Collaboration Update",
    message: "Jane added new items to Dubai trip itinerary",
    time: "2 days ago",
    read: true,
  },
  {
    id: 5,
    type: "booking",
    title: "Booking Confirmed",
    message: "Your W Goa hotel booking is confirmed",
    time: "3 days ago",
    read: true,
  },
];

export const currentUser = {
  id: 1,
  name: "John Doe",
  email: "john.doe@email.com",
  avatar: "https://i.pravatar.cc/150?img=1",
  phone: "+91 98765 43210",
  preferences: {
    currency: "INR",
    language: "English",
    notifications: {
      email: true,
      push: true,
      sms: false,
    },
  },
  savedCards: [
    { id: 1, type: "visa", last4: "4242", expiry: "12/25" },
    { id: 2, type: "mastercard", last4: "8888", expiry: "03/26" },
  ],
  savedPlaces: ["Goa", "Dubai", "Bali"],
  recentSearches: [
    { type: "flight", from: "Delhi", to: "Goa", date: "2024-03-15" },
    { type: "hotel", location: "Mumbai", checkIn: "2024-03-20" },
  ],
};

export const cities = [
  "Delhi", "Mumbai", "Bangalore", "Chennai", "Kolkata", "Hyderabad",
  "Goa", "Jaipur", "Udaipur", "Agra", "Varanasi", "Kochi", "Manali",
  "Shimla", "Darjeeling", "Andaman", "Leh", "Rishikesh", "Mysore",
  "Dubai", "Singapore", "Bangkok", "Bali", "Maldives", "Sri Lanka",
  "Nepal", "Bhutan", "Vietnam", "Malaysia", "Hong Kong", "Tokyo"
];

export const railwayStations = [
  { name: "New Delhi", code: "NDLS", city: "Delhi" },
  { name: "Mumbai Central", code: "MMCT", city: "Mumbai" },
  { name: "Howrah Junction", code: "HWH", city: "Kolkata" },
  { name: "Chennai Central", code: "MAS", city: "Chennai" },
  { name: "Bangalore City", code: "SBC", city: "Bangalore" },
  { name: "Hyderabad", code: "HYB", city: "Hyderabad" },
  { name: "Jaipur Junction", code: "JP", city: "Jaipur" },
  { name: "Agra Cantt", code: "AGC", city: "Agra" },
  { name: "Varanasi Junction", code: "BSB", city: "Varanasi" },
  { name: "Lucknow", code: "LKO", city: "Lucknow" },
  { name: "Pune Junction", code: "PUNE", city: "Pune" },
  { name: "Ahmedabad Junction", code: "ADI", city: "Ahmedabad" },
];

export const airlines = ["IndiGo", "Air India", "Vistara", "SpiceJet", "GoFirst", "Emirates", "Singapore Airlines", "Thai Airways"];
export const hotelAmenities = ["WiFi", "Pool", "Spa", "Gym", "Restaurant", "Bar", "Parking", "Room Service", "Beach Access", "Pet Friendly"];
export const activityCategories = ["Adventure", "Cultural", "Nature", "Wildlife", "Food", "Nightlife", "Shopping", "Wellness"];
export const trainClasses = ["1A", "2A", "3A", "SL", "EC", "CC"];
export const cabTypes = ["Sedan", "SUV", "Luxury", "Tempo Traveller"];

// Special fare categories
export const specialFares = [
  { id: "regular", name: "Regular", description: "Regular fares" },
  { id: "student", name: "Student", description: "Extra discounts/baggage", discount: 10 },
  { id: "armed_forces", name: "Armed Forces", description: "Up to ₹600 off", discount: 600 },
  { id: "senior", name: "Senior Citizen", description: "Up to ₹600 off", discount: 600 },
  { id: "doctor", name: "Doctor and Nurses", description: "Up to ₹600 off", discount: 600 },
];
